# Server
#server.port=8080

# SQL Server (sửa lại cho đúng với máy bạn)
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarWashDB;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=123456  # Thay bằng mật khẩu SQL Server thật
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA (cho SQL Server – tạm comment)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==============================
#  SERVER
# ==============================
server.port=8080

# DATASOURCE (Azure)
spring.datasource.url=jdbc:sqlserver://autowash-pro.database.windows.net:1433;database=AutoWashPro;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=admin1@autowash-pro
spring.datasource.password=$A12345678
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false


# ==============================
#  JWT
# ==============================
app.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation2025!VeryLongAndSecure
app.jwt.expiration-milliseconds=86400000
app.jwt.refresh-expiration-milliseconds=604800000

# ==============================
#  LOGGING
# ==============================
logging.level.com.carwash=DEBUG

# ==============================
#  EMAIL CONFIGURATION
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=yennhi.ln230405@gmail.com
spring.mail.password=tqtc qvkw ldpq onub

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# ==============================
#  BASE URL
# ==============================
app.base-url=http://localhost:8080

# ==============================
# PAYOS
# ==============================

payos.client-id=xxxxxxxxxxxxxxxx
payos.api-key=xxxxxxxxxxxxxxxx
payos.checksum-key=xxxxxxxxxxxxxxxx

payos.return-url=http://localhost:8080/payment/return
payos.cancel-url=http://localhost:8080/payment/cancel


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


google.client-id=113961981076-sdd3hoa1su780ipt519vb6cagpbaemfc.apps.googleusercontent.com


